
auth_controllers:
  resource: ../src/Auth/Controller/
  type: attribute
  prefix: /api/auth

session_controllers:
  resource: ../src/Session/Controller/
  type: attribute
  prefix: /api/session

task_controllers:
  resource: ../src/Task/Controller/
  type: attribute
  prefix: /api/task

player_controllers:
  resource: ../src/Player/Controller/
  type: attribute
  prefix: /api/player
