session_controllers:
  resource: ../src/Session/Controller/
  type: attribute
  prefix: /session

task_controllers:
  resource: ../src/Task/Controller/
  type: attribute
  prefix: /task

player_controllers:
  resource: ../src/Player/Controller/
  type: attribute
  prefix: /player
